NEW = {"fa": {}, "en": {}}
def add(key, fa, en):
    NEW["fa"][key] = fa; NEW["en"][key] = en
add("b_edit", "✏️ ویرایش استیکر", "✏️ Edit sticker")
add("b_me", "👤 حساب من", "👤 My account")
add("b_invite", "🎁 دعوت دوستان", "🎁 Invite friends")
add("b_rm", "🗑 حذف استیکر از پک", "🗑 Remove from pack")
add("b_emo", "😀 ویرایش ایموجی", "😀 Edit emoji")
add("b_mode", "🧪 پیش‌نمایش قبل از افزودن: {s}", "🧪 Preview before adding: {s}")
add("on", "روشن", "on"); add("off", "خاموش", "off")
add("on", "روشن", "on"); add("off", "خاموش", "off")
add("on", "روشن", "on"); add("off", "خاموش", "off")
add("on", "روشن", "on"); add("off", "خاموش", "off")
add("b_admin", "🛠 پنل ادمین", "🛠 Admin panel")
add("e_text", "📝 متن", "📝 Text")
add("e_rot", "↻ چرخش ۹۰°", "↻ Rotate 90°")
add("e_flip", "↔️ آینه‌ای", "↔️ Flip")
add("e_undo", "↩️ بازگردانی", "↩️ Undo")
add("e_reset", "🔄 تصویر اصلی", "🔄 Reset")
add("e_add", "✅ افزودن به پک", "✅ Add to pack")
add("e_upd", "🔁 به‌روزرسانی در پک", "🔁 Update in pack")
add("e_dellast", "🗑 حذف آخرین استیکر پک", "🗑 Delete last sticker")
add("e_top", "⬆️ بالا", "⬆️ Top"); add("e_center", "⏺ وسط", "⏺ Middle"); add("e_bottom", "⬇️ پایین", "⬇️ Bottom")
add("e_top", "⬆️ بالا", "⬆️ Top"); add("e_center", "⏺ وسط", "⏺ Middle"); add("e_bottom", "⬇️ پایین", "⬇️ Bottom")
add("e_top", "⬆️ بالا", "⬆️ Top"); add("e_center", "⏺ وسط", "⏺ Middle"); add("e_bottom", "⬇️ پایین", "⬇️ Bottom")
add("e_top", "⬆️ بالا", "⬆️ Top"); add("e_center", "⏺ وسط", "⏺ Middle"); add("e_bottom", "⬇️ پایین", "⬇️ Bottom")
add("e_top", "⬆️ بالا", "⬆️ Top"); add("e_center", "⏺ وسط", "⏺ Middle"); add("e_bottom", "⬇️ پایین", "⬇️ Bottom")
add("e_top", "⬆️ بالا", "⬆️ Top"); add("e_center", "⏺ وسط", "⏺ Middle"); add("e_bottom", "⬇️ پایین", "⬇️ Bottom")
add("e_top", "⬆️ بالا", "⬆️ Top"); add("e_center", "⏺ وسط", "⏺ Middle"); add("e_bottom", "⬇️ پایین", "⬇️ Bottom")
add("e_top", "⬆️ بالا", "⬆️ Top"); add("e_center", "⏺ وسط", "⏺ Middle"); add("e_bottom", "⬇️ پایین", "⬇️ Bottom")
add("e_top", "⬆️ بالا", "⬆️ Top"); add("e_center", "⏺ وسط", "⏺ Middle"); add("e_bottom", "⬇️ پایین", "⬇️ Bottom")
add("yes", "✅ بله", "✅ Yes"); add("no", "✖️ نه", "✖️ No")
add("yes", "✅ بله", "✅ Yes"); add("no", "✖️ نه", "✖️ No")
add("yes", "✅ بله", "✅ Yes"); add("no", "✖️ نه", "✖️ No")
add("yes", "✅ بله", "✅ Yes"); add("no", "✖️ نه", "✖️ No")
add("edit_intro", "✏️ ابزارهای ویرایش اینجاست! هر تغییر را روی پیش‌نمایش ببین و در پایان «{final}» را بزن 👇",
    "✏️ Editing tools are here! Check each change on the preview, then tap “{final}” 👇")
add("edit_none", "هنوز استیکری برای ویرایش نداری 🙈 اول یک عکس بفرست.", "You have no sticker to edit yet 🙈 Send an image first.")
add("ask_text", "📝 متنی را که می‌خواهی روی استیکر بنویسی بفرست (فارسی یا انگلیسی، حداکثر ۱۲۰ کاراکتر):\n(برای انصراف /cancel)",
    "📝 Send the text to put on the sticker (Persian or English, up to 120 chars):\n(/cancel to abort)")
add("text_bad", "متن خالی یا نامعتبر است. دوباره بفرست یا /cancel.", "Empty or invalid text. Send it again or /cancel.")
add("ask_pos", "متن کجا قرار بگیرد؟", "Where should the text go?")
add("ask_emoji_cur", "😀 یک تا ۲۰ ایموجی برای این استیکر بفرست:", "😀 Send 1 to 20 emojis for this sticker:")
add("ask_emoji_pick", "😀 استیکری را که می‌خواهی ایموجی‌اش عوض شود از پکت برایم بفرست (یا روی آن ریپلای کن و /emoji بزن).",
    "😀 Send me the sticker from your pack whose emoji you want to change (or reply to it with /emoji).")
add("ask_emoji_new", "حالا یک تا ۲۰ ایموجی جدید بفرست:", "Now send 1 to 20 new emojis:")
add("emoji_bad", "فقط ایموجی بفرست (بین ۱ تا ۲۰ عدد) 🙂", "Please send emojis only (1 to 20) 🙂")
add("emoji_set", "✅ ایموجی‌ها تغییر کرد: {emoji}", "✅ Emoji updated: {emoji}")
add("emoji_fail", "⚠️ تغییر ایموجی ناموفق بود.\n{err}", "⚠️ Couldn't change the emoji.\n{err}")
add("emoji_draft", "✅ ایموجی این استیکر: {emoji} (با افزودن به پک اعمال می‌شود)", "✅ Sticker emoji: {emoji} (applied when added to the pack)")
add("rm_ask", "🗑 استیکری را که می‌خواهی از پکت حذف شود برایم بفرست (یا روی آن ریپلای کن و /delsticker بزن).",
    "🗑 Send me the sticker you want to remove from your pack (or reply to it with /delsticker).")
add("rm_done", "🗑 استیکر از پک حذف شد. حالا {count} استیکر داری.", "🗑 Sticker removed from the pack. It now has {count} stickers.")
add("rm_done_empty", "🗑 استیکر حذف شد و پک خالی شد؛ با فرستادن عکس بعدی پک جدید ساخته می‌شود.",
    "🗑 Sticker removed; the pack is now empty, so a new one will be created with your next image.")
add("rm_not_yours", "این استیکر متعلق به پک‌های ساخته‌شده با این ربات برای تو نیست 🙅", "That sticker isn't from a pack this bot made for you 🙅")
add("rm_fail", "⚠️ حذف ناموفق بود.\n{err}", "⚠️ Couldn't remove it.\n{err}")
add("need_sticker_reply", "روی یک استیکر ریپلای کن و دستور را بفرست، یا از منو استفاده کن.", "Reply to a sticker with this command, or use the menu.")
add("dellast_confirm", "مطمئنی آخرین استیکر پک حذف شود؟", "Delete the last sticker of your pack?")
add("dellast_none", "پکی برای حذف ندارم 🤷", "There's no pack to delete from 🤷")
add("edit_added", "✅ به پک اضافه شد {emoji}\n🔗 {url}", "✅ Added to the pack {emoji}\n🔗 {url}")
add("edit_updated", "🔁 استیکر در پک به‌روز شد {emoji}\n🔗 {url}", "🔁 Sticker updated in the pack {emoji}\n🔗 {url}")
add("edit_fail", "⚠️ انجام نشد.\n{err}", "⚠️ That didn't work.\n{err}")
add("undo_nothing", "چیزی برای بازگردانی نیست.", "Nothing to undo.")
add("reset_done", "🔄 به تصویر اصلی برگشتیم.", "🔄 Back to the original image.")
add("mode_changed", "🧪 پیش‌نمایش قبل از افزودن: {s}\n(وقتی روشن باشد عکس‌ها اول پیش‌نمایش و ابزار ویرایش می‌گیرند و با دکمه‌ی «افزودن» وارد پک می‌شوند.)",
    "🧪 Preview before adding: {s}\n(When on, images show a preview with editing tools first and are added with the “Add” button.)")
add("preview_ready", "✨ آماده است. ویرایش کن و بعد «افزودن به پک» را بزن.", "✨ Ready. Edit it, then tap “Add to pack”.")
add("draft_info", "📐 {w}×{h} · 🗜 {final}", "📐 {w}×{h} · 🗜 {final}")
add("quota_out_ref", "یا دوستانت را دعوت کن و اعتبار هدیه بگیر 🎁", "or invite friends to earn free credits 🎁")
add("me_head", "👤 حساب تو", "👤 Your account")
add("me_admin", "👑 نقش: ادمین (نامحدود)", "👑 Role: admin (unlimited)")
add("me_unl", "♾ دسترسی: نامحدود", "♾ Access: unlimited")
add("me_until", "📅 دسترسی نامحدود تا: {date}", "📅 Unlimited until: {date}")
add("me_free", "🆓 سهمیه‌ی رایگان باقی‌مانده: {n} از {total}", "🆓 Free quota left: {n} of {total}")
add("me_made", "🖼 استیکرهای ساخته‌شده: {n}", "🖼 Stickers made: {n}")
add("me_ref", "🎁 دعوت‌شده‌ها: {n} نفر · پاداش گرفته: {b} استیکر", "🎁 Invited: {n} · bonus earned: {b} stickers")
add("invite_text", "🎁 دعوت دوستان\n\nلینک اختصاصی تو:\n{link}\n\nهر دوستِ جدیدی که با این لینک وارد ربات شود، {bonus} استیکر هدیه می‌گیری" 
    "{invitee_line} 🎉\n\n👥 دعوت‌شده‌ها: {n}\n💎 پاداش گرفته‌شده: {earned} استیکر",
    "🎁 Invite friends\n\nYour personal link:\n{link}\n\nFor every brand-new friend who joins with it you get {bonus} free stickers"
    "{invitee_line} 🎉\n\n👥 Invited: {n}\n💎 Bonus earned: {earned} stickers")
add("invite_invitee_line", " (و دوستت هم {b} استیکر هدیه می‌گیرد)", " (and your friend gets {b} too)")
add("invite_off", "🎁 سیستم دعوت فعلاً غیرفعال است.", "🎁 The referral program is currently off.")
add("ref_joined_referrer", "🎉 یک دوست جدید با لینک تو آمد! {bonus} استیکر هدیه گرفتی 🎁", "🎉 A new friend joined with your link! You got {bonus} free stickers 🎁")
add("ref_joined_invitee", "🎁 چون با لینک دعوت آمدی، {bonus} استیکر هدیه گرفتی!", "🎁 You joined via an invite link, so you got {bonus} free stickers!")
add("a_title", "🛠 پنل ادمین — یکی را انتخاب کن:", "🛠 Admin panel — pick one:")
add("a_b_stats", "📊 آمار", "📊 Stats"); add("a_b_users", "👥 کاربران", "👥 Users")
add("a_b_stats", "📊 آمار", "📊 Stats"); add("a_b_users", "👥 کاربران", "👥 Users")
add("a_b_stats", "📊 آمار", "📊 Stats"); add("a_b_users", "👥 کاربران", "👥 Users")
add("a_b_stats", "📊 آمار", "📊 Stats"); add("a_b_users", "👥 کاربران", "👥 Users")
add("a_b_grant", "🎁 اعطای دسترسی", "🎁 Grant access"); add("a_b_revoke", "⛔ لغو دسترسی", "⛔ Revoke")
add("a_b_grant", "🎁 اعطای دسترسی", "🎁 Grant access"); add("a_b_revoke", "⛔ لغو دسترسی", "⛔ Revoke")
add("a_b_grant", "🎁 اعطای دسترسی", "🎁 Grant access"); add("a_b_revoke", "⛔ لغو دسترسی", "⛔ Revoke")
add("a_b_grant", "🎁 اعطای دسترسی", "🎁 Grant access"); add("a_b_revoke", "⛔ لغو دسترسی", "⛔ Revoke")
add("a_b_credits", "➕ افزودن اعتبار", "➕ Add credits"); add("a_b_settings", "⚙️ تنظیمات", "⚙️ Settings")
add("a_b_credits", "➕ افزودن اعتبار", "➕ Add credits"); add("a_b_settings", "⚙️ تنظیمات", "⚙️ Settings")
add("a_b_credits", "➕ افزودن اعتبار", "➕ Add credits"); add("a_b_settings", "⚙️ تنظیمات", "⚙️ Settings")
add("a_b_credits", "➕ افزودن اعتبار", "➕ Add credits"); add("a_b_settings", "⚙️ تنظیمات", "⚙️ Settings")
add("a_b_bc", "📢 پیام همگانی", "📢 Broadcast")
add("a_b_ref", "🎁 دعوت‌ها", "🎁 Referrals"); add("a_back", "⬅️ بازگشت", "⬅️ Back"); add("a_home", "🛠 پنل", "🛠 Panel")
add("a_b_ref", "🎁 دعوت‌ها", "🎁 Referrals"); add("a_back", "⬅️ بازگشت", "⬅️ Back"); add("a_home", "🛠 پنل", "🛠 Panel")
add("a_b_ref", "🎁 دعوت‌ها", "🎁 Referrals"); add("a_back", "⬅️ بازگشت", "⬅️ Back"); add("a_home", "🛠 پنل", "🛠 Panel")
add("a_b_ref", "🎁 دعوت‌ها", "🎁 Referrals"); add("a_back", "⬅️ بازگشت", "⬅️ Back"); add("a_home", "🛠 پنل", "🛠 Panel")
add("a_b_ref", "🎁 دعوت‌ها", "🎁 Referrals"); add("a_back", "⬅️ بازگشت", "⬅️ Back"); add("a_home", "🛠 پنل", "🛠 Panel")
add("a_b_ref", "🎁 دعوت‌ها", "🎁 Referrals"); add("a_back", "⬅️ بازگشت", "⬅️ Back"); add("a_home", "🛠 پنل", "🛠 Panel")
add("a_b_ref", "🎁 دعوت‌ها", "🎁 Referrals"); add("a_back", "⬅️ بازگشت", "⬅️ Back"); add("a_home", "🛠 پنل", "🛠 Panel")
add("a_b_ref", "🎁 دعوت‌ها", "🎁 Referrals"); add("a_back", "⬅️ بازگشت", "⬅️ Back"); add("a_home", "🛠 پنل", "🛠 Panel")
add("a_b_ref", "🎁 دعوت‌ها", "🎁 Referrals"); add("a_back", "⬅️ بازگشت", "⬅️ Back"); add("a_home", "🛠 پنل", "🛠 Panel")
add("a_stats", "📊 آمار\n\n👥 کل کاربران: {users}\n🟢 فعال (۷ روز اخیر): {active}\n🖼 استیکرهای ساخته‌شده: {made}\n♾ کاربران با دسترسی نامحدود: {unl}\n🎁 دعوت‌های موفق: {refs}",
    "📊 Stats\n\n👥 Total users: {users}\n🟢 Active (last 7 days): {active}\n🖼 Stickers made: {made}\n♾ Users with unlimited access: {unl}\n🎁 Successful referrals: {refs}")
add("a_users_head", "👥 کاربران — صفحه‌ی {p} از {pages} (کل: {n})", "👥 Users — page {p} of {pages} (total {n})")
add("a_users_none", "هنوز کاربری نیست.", "No users yet.")
add("a_prev", "◀️", "◀️"); add("a_next", "▶️", "▶️")
add("a_prev", "◀️", "◀️"); add("a_next", "▶️", "▶️")
add("a_prev", "◀️", "◀️"); add("a_next", "▶️", "▶️")
add("a_prev", "◀️", "◀️"); add("a_next", "▶️", "▶️")
add("a_user", "👤 {name} {uname}\n🆔 {uid}\n🌐 زبان: {ulang}\n📅 اولین بار: {first}\n🖼 ساخته‌شده: {made}\n{status}\n🎁 دعوت‌شده‌ها: {refs}",
    "👤 {name} {uname}\n🆔 {uid}\n🌐 Language: {ulang}\n📅 First seen: {first}\n🖼 Made: {made}\n{status}\n🎁 Referred: {refs}")
add("a_status_admin", "👑 ادمین", "👑 Admin")
add("a_status_unl", "♾ نامحدود (اعطایی)", "♾ Unlimited (granted)")
add("a_status_until", "📅 نامحدود تا {date} · اعتبار: {c}", "📅 Unlimited until {date} · credits: {c}")
add("a_status_quota", "🆓 رایگان باقی‌مانده: {f} · 💎 اعتبار: {c}", "🆓 Free left: {f} · 💎 credits: {c}")
add("a_op_grant", "♾ نامحدود دائمی", "♾ Unlimited forever"); add("a_op_days", "📅 نامحدود N روز", "📅 Unlimited N days")
add("a_op_grant", "♾ نامحدود دائمی", "♾ Unlimited forever"); add("a_op_days", "📅 نامحدود N روز", "📅 Unlimited N days")
add("a_op_grant", "♾ نامحدود دائمی", "♾ Unlimited forever"); add("a_op_days", "📅 نامحدود N روز", "📅 Unlimited N days")
add("a_op_grant", "♾ نامحدود دائمی", "♾ Unlimited forever"); add("a_op_days", "📅 نامحدود N روز", "📅 Unlimited N days")
add("a_op_revoke", "⛔ لغو دسترسی", "⛔ Revoke"); add("a_op_credits", "➕ افزودن اعتبار", "➕ Add credits")
add("a_op_revoke", "⛔ لغو دسترسی", "⛔ Revoke"); add("a_op_credits", "➕ افزودن اعتبار", "➕ Add credits")
add("a_op_revoke", "⛔ لغو دسترسی", "⛔ Revoke"); add("a_op_credits", "➕ افزودن اعتبار", "➕ Add credits")
add("a_op_revoke", "⛔ لغو دسترسی", "⛔ Revoke"); add("a_op_credits", "➕ افزودن اعتبار", "➕ Add credits")
add("a_ask_target", "🆔 شناسه‌ی عددی یا @نام‌کاربری کاربر را بفرست (باید قبلاً با ربات کار کرده باشد):\n(/cancel برای انصراف)",
    "🆔 Send the user's numeric id or @username (they must have used the bot before):\n(/cancel to abort)")
add("a_not_found", "❌ این کاربر را پیدا نکردم (ربات او را ندیده است).", "❌ I couldn't find that user (the bot hasn't seen them).")
add("a_ask_num", "یک عدد بفرست ({what}):", "Send a number ({what}):")
add("a_what_days", "تعداد روز", "number of days"); add("a_what_credits", "تعداد استیکر", "number of stickers")
add("a_what_days", "تعداد روز", "number of days"); add("a_what_credits", "تعداد استیکر", "number of stickers")
add("a_what_days", "تعداد روز", "number of days"); add("a_what_credits", "تعداد استیکر", "number of stickers")
add("a_what_days", "تعداد روز", "number of days"); add("a_what_credits", "تعداد استیکر", "number of stickers")
add("a_bad_num", "عدد نامعتبر است. دوباره بفرست یا /cancel.", "Invalid number. Send again or /cancel.")
add("a_choose_grant", "کدام دسترسی برای {who}؟", "Which access for {who}?")
add("a_confirm_revoke", "دسترسی و اعتبار {who} لغو شود؟ (به سهمیه‌ی رایگان برمی‌گردد)", "Revoke {who}'s access and credits? (falls back to the free quota)")
add("a_done_grant", "✅ دسترسی نامحدود دائمی برای {who} فعال شد.", "✅ Permanent unlimited access granted to {who}.")
add("a_done_days", "✅ {n} روز دسترسی نامحدود برای {who} ثبت شد (تا {date}).", "✅ {n} days of unlimited access added for {who} (until {date}).")
add("a_done_revoke", "✅ دسترسی {who} لغو شد.", "✅ Access revoked for {who}.")
add("a_done_credits", "✅ {n} استیکر اعتبار به {who} اضافه شد.", "✅ Added {n} sticker credits to {who}.")
add("u_granted", "🎁 ادمین دسترسی نامحدود به تو داد! هر چقدر دلت خواست استیکر بساز 🥳", "🎁 The admin gave you unlimited access! Make as many stickers as you like 🥳")
add("u_days", "🎁 ادمین {n} روز دسترسی نامحدود به تو داد (تا {date}) 🥳", "🎁 The admin gave you {n} days of unlimited access (until {date}) 🥳")
add("u_revoked", "ℹ️ دسترسی ویژه‌ی تو توسط ادمین لغو شد.", "ℹ️ Your special access was revoked by the admin.")
add("u_credits", "🎁 ادمین {n} استیکر اعتبار به تو اضافه کرد 💎", "🎁 The admin added {n} sticker credits to your account 💎")
add("a_notset", "(تنظیم نشده)", "(not set)")
add("a_s_quota", "🆓 سهمیه‌ی رایگان", "🆓 Free quota")
add("a_s_rb", "➕ پاداش دعوت‌کننده", "➕ Referrer bonus"); add("a_s_ib", "➕ پاداش دعوت‌شده", "➕ Invitee bonus")
add("a_s_rb", "➕ پاداش دعوت‌کننده", "➕ Referrer bonus"); add("a_s_ib", "➕ پاداش دعوت‌شده", "➕ Invitee bonus")
add("a_s_reftoggle", "🎁 دعوت‌ها: {s}", "🎁 Referrals: {s}")
add("a_s_ask_num", "مقدار جدید را به صورت عدد بفرست (۰ تا ۱۰۰۰۰۰):", "Send the new value as a number (0 to 100000):")
add("a_s_saved", "✅ ذخیره شد.", "✅ Saved.")
add("a_bc_ask", "📢 متن پیام همگانی را بفرست:\n(/cancel برای انصراف)", "📢 Send the broadcast text:\n(/cancel to abort)")
add("a_bc_confirm", "📢 پیش‌نمایش پیام همگانی:\n\n{text}\n\n➡️ برای {n} کاربر ارسال شود؟", "📢 Broadcast preview:\n\n{text}\n\n➡️ Send to {n} users?")
add("a_bc_sending", "⏳ ارسال شروع شد…", "⏳ Sending started…")
add("a_bc_done", "📢 ارسال تمام شد: ✅ {ok} موفق · ❌ {fail} ناموفق", "📢 Broadcast finished: ✅ {ok} sent · ❌ {fail} failed")
add("a_bc_cancel", "لغو شد.", "Cancelled.")
add("a_bc_none", "پیش‌نویسی برای ارسال نیست.", "No pending broadcast.")
add("a_ref", "🎁 دعوت‌ها\n\nوضعیت: {s}\n👥 کل دعوت‌ها: {total}\n➕ پاداش دعوت‌کننده: {rb}\n➕ پاداش دعوت‌شده: {ib}\n\n🏆 برترین دعوت‌کننده‌ها:\n{top}",
    "🎁 Referrals\n\nStatus: {s}\n👥 Total referrals: {total}\n➕ Referrer bonus: {rb}\n➕ Invitee bonus: {ib}\n\n🏆 Top referrers:\n{top}")
add("a_ref_none", "— هنوز کسی نیست —", "— nobody yet —")
add("a_bound", "👑 شناسه‌ی عددی تو ({uid}) به‌عنوان ادمین ثبت شد. از این پس فقط با شناسه‌ی عددی احراز می‌شوی. /admin را بزن.",
    "👑 Your numeric id ({uid}) is now registered as admin. From now on you're authorized by numeric id only. Send /admin.")
add("b_tools", "🧰 ابزار پک", "🧰 Pack tools")
add("tools_title", "🧰 ابزار پک — یکی را انتخاب کن 👇", "🧰 Pack tools — pick one 👇")
add("help_extra",
    "\n\n✨ امکانات بیشتر:\n/edit — ویرایش آخرین استیکر (متن، چرخش، آینه، ایموجی)\n/emoji — تغییر ایموجی یک استیکر پک (روی استیکر ریپلای کن)\n/delsticker — حذف استیکر از پک (روی آن ریپلای کن)\n/me — حساب و سهمیه‌ی من\n/invite — دعوت دوستان و گرفتن هدیه\n/id — نمایش شناسه‌ی عددی من",
    "\n\n✨ More features:\n/edit — edit your last sticker (text, rotate, flip, emoji)\n/emoji — change a pack sticker's emoji (reply to the sticker)\n/delsticker — remove a sticker from the pack (reply to it)\n/me — my account & quota\n/invite — invite friends for free credits\n/id — show my numeric ID")
add("b_contact", "💬 پیام به ادمین", "💬 Contact admin")
add("quota_out",
    "🙈 وای! سهمیه‌ی استیکر رایگانت تمام شد!\n\n{price}💌 برای ادامه به ادمین پیام بده و این شناسه‌ی عددی‌ات را همراهش بفرست تا حسابت را فعال کند:\n🆔 <code>{uid}</code>\n(روی شناسه بزن تا کپی شود 😉){note}",
    "🙈 Oh no! You've used up your free stickers!\n\n{price}💌 To keep going, message the admin and include your numeric ID so they can activate your account:\n🆔 <code>{uid}</code>\n(tap the ID to copy it 😉){note}")
add("me_id", "🆔 شناسه‌ی عددی تو: <code>{uid}</code>", "🆔 Your numeric ID: <code>{uid}</code>")
add("me_credits", "💎 اعتبار هدیه/افزوده‌شده: {n}", "💎 Bonus credits: {n}")
add("a_settings", "⚙️ تنظیمات\n\n🆓 سهمیه‌ی رایگان هر کاربر: {quota}\n🎁 دعوت‌ها: {ref}\n➕ پاداش دعوت‌کننده: {rb}\n➕ پاداش دعوت‌شده: {ib}\n💰 قیمت: {price}",
    "⚙️ Settings\n\n🆓 Free quota per user: {quota}\n🎁 Referrals: {ref}\n➕ Referrer bonus: {rb}\n➕ Invitee bonus: {ib}\n💰 Price: {price}")
add("b_share", "📤 اشتراک‌گذاری", "📤 Share")
add("invite_share_text",
    "🌸 سلام! یه ربات خیلی بامزه پیدا کردم که هر عکسی رو توی چند ثانیه به استیکر تلگرام تبدیل می‌کنه ✨\n🖼 حجم عکس رو خودش کم می‌کنه، می‌تونی روش متن فارسی بنویسی، ایموجی بذاری و مستقیم توی پک استیکر خودت ذخیره‌ش کنی 💖\n🎁 با این لینک وارد شو تا استیکر رایگان هدیه بگیری:",
    "🌸 Hey! I found the cutest bot that turns any photo into a Telegram sticker in seconds ✨\n🖼 It shrinks the file size for you, lets you add text and emojis, and saves it straight into your own sticker pack 💖\n🎁 Join with my link and get free stickers as a gift:")
add("invite_forward_hint", "👇 این پیام آماده‌ی فوروارد است؛ برای دوستانت بفرست یا دکمه‌ی اشتراک‌گذاری را بزن:",
    "👇 This message is ready to forward — send it to your friends or tap Share:")
add("a_s_price", "💰 تنظیم قیمت", "💰 Set price")
add("a_price_menu", "💰 قیمت\n\nفارسی: {fa}\nEnglish: {en}\n\nیک متن ساده (هر چه می‌خواهی کاربران ببینند) تنظیم کن. این متن بالای شناسه و دکمه‌ی «پیام به ادمین» نشان داده می‌شود.",
    "💰 Price\n\nفارسی: {fa}\nEnglish: {en}\n\nSet one free-text line (anything you want users to see). It's shown above the user's ID and the “Contact admin” button.")
add("a_price_both", "✏️ یک متن برای هر دو زبان", "✏️ One text for both languages")
add("a_price_fa", "🇮🇷 فقط فارسی", "🇮🇷 Persian only")
add("a_price_en", "🇬🇧 فقط انگلیسی", "🇬🇧 English only")
add("a_price_clear", "🧹 پاک کردن قیمت", "🧹 Clear price")
add("a_price_ask", "💰 متن قیمت جدید را بفرست ({which}):\n(/cancel برای انصراف)", "💰 Send the new price text ({which}):\n(/cancel to abort)")
add("a_price_which_both", "برای هر دو زبان", "used for both languages")
add("a_price_which_fa", "فقط فارسی", "Persian only")
add("a_price_which_en", "فقط انگلیسی", "English only")
add("a_price_saved", "✅ قیمت ذخیره شد:\n{text}", "✅ Price saved:\n{text}")
add("a_price_cleared", "🧹 قیمت پاک شد؛ دیگر چیزی درباره‌ی قیمت نشان داده نمی‌شود.", "🧹 Price cleared; nothing about price is shown now.")
add("a_price_unset", "(تنظیم نشده)", "(not set)")
add("price_line", "💰 {text}", "💰 {text}")
add("a_b_prices", "💰 قیمت‌ها", "💰 Prices")
add("pp_head_user", "💰 پلن‌ها:", "💰 Plans:")
add("pp_none", "— هنوز پلنی تعریف نشده —", "— no plans yet —")
add("pp_add", "➕ افزودن پلن", "➕ Add plan"); add("pp_edit", "✏️ ویرایش", "✏️ Edit"); add("pp_del", "🗑 حذف", "🗑 Delete")
add("pp_add", "➕ افزودن پلن", "➕ Add plan"); add("pp_edit", "✏️ ویرایش", "✏️ Edit"); add("pp_del", "🗑 حذف", "🗑 Delete")
add("pp_add", "➕ افزودن پلن", "➕ Add plan"); add("pp_edit", "✏️ ویرایش", "✏️ Edit"); add("pp_del", "🗑 حذف", "🗑 Delete")
add("pp_clear", "🧹 پاک کردن همه", "🧹 Clear all"); add("pp_note", "📝 متن قیمت ساده", "📝 Simple price line")
add("pp_clear", "🧹 پاک کردن همه", "🧹 Clear all"); add("pp_note", "📝 متن قیمت ساده", "📝 Simple price line")
add("pp_full", "به سقف {n} پلن رسیدی؛ اول یکی را حذف کن.", "You've reached the limit of {n} plans; delete one first.")
add("pp_deleted", "🗑 پلن حذف شد.", "🗑 Plan deleted.")
add("pp_cleared", "🧹 همه‌ی پلن‌ها پاک شد.", "🧹 All plans cleared.")
add("pp_clear_confirm", "همه‌ی پلن‌ها پاک شوند؟", "Clear all plans?")
add("pp_e_title", "✏️ عنوان", "✏️ Title"); add("pp_e_price", "💵 قیمت", "💵 Price"); add("pp_e_grant", "🎁 اعطا", "🎁 Grant link")
add("pp_e_title", "✏️ عنوان", "✏️ Title"); add("pp_e_price", "💵 قیمت", "💵 Price"); add("pp_e_grant", "🎁 اعطا", "🎁 Grant link")
add("pp_gone", "این پلن دیگر وجود ندارد.", "That plan no longer exists.")
add("pp_free_line", "🆓 رایگان — {n} استیکر", "🆓 Free — {n} stickers")
add("pp_what_credits", "{n} استیکر", "{n} stickers")
add("b_support1", "💬 پشتیبان ۱", "💬 Support 1"); add("b_support2", "💬 پشتیبان ۲", "💬 Support 2")
add("b_support1", "💬 پشتیبان ۱", "💬 Support 1"); add("b_support2", "💬 پشتیبان ۲", "💬 Support 2")
add("support_note", "\n\n🛟 اگر پشتیبان اول در دسترس نبود، به پشتیبان دوم پیام بده 💕", "\n\n🛟 If the first support isn't available, message the second one 💕")
add("a_b_admins", "👮 ادمین‌ها", "👮 Admins"); add("a_b_support", "💬 پشتیبانی", "💬 Support contacts")
add("a_b_admins", "👮 ادمین‌ها", "👮 Admins"); add("a_b_support", "💬 پشتیبانی", "💬 Support contacts")
add("ad_menu", "👮 مدیریت ادمین‌ها\n\n👑 مالک: {owner}\n\n👮 ادمین‌های اضافه:\n{lines}\n\nادمین‌های اضافه می‌توانند آمار و کاربران را ببینند و دسترسی بدهند/لغو کنند/اعتبار اضافه کنند؛ ولی نمی‌توانند ادمین‌ها، تنظیمات، قیمت‌ها یا پیام همگانی را مدیریت کنند.",
    "👮 Manage admins\n\n👑 Owner: {owner}\n\n👮 Extra admins:\n{lines}\n\nExtra admins can view stats & users and grant/revoke/add credits, but can't manage admins, settings, prices or broadcast.")
add("ad_none", "— هنوز کسی نیست —", "— nobody yet —")
add("ad_add", "➕ افزودن ادمین", "➕ Add admin"); add("ad_owner", "🔁 تغییر شناسه‌ی مالک", "🔁 Change owner ID")
add("ad_add", "➕ افزودن ادمین", "➕ Add admin"); add("ad_owner", "🔁 تغییر شناسه‌ی مالک", "🔁 Change owner ID")
add("ad_ask_add", "🆔 شناسه‌ی عددی یا @نام‌کاربری ادمین جدید را بفرست (باید قبلاً با ربات کار کرده باشد):\n(/cancel برای انصراف)",
    "🆔 Send the new admin's numeric id or @username (they must have used the bot before):\n(/cancel to abort)")
add("ad_added", "✅ {who} به ادمین‌ها اضافه شد.", "✅ {who} was added as admin.")
add("ad_is_owner", "این کاربر همین الان مالک است 👑", "That user is already the owner 👑")
add("ad_removed", "🗑 {who} از ادمین‌ها حذف شد.", "🗑 {who} was removed from admins.")
add("ad_notify_new", "👮 تو به‌عنوان ادمین ربات انتخاب شدی! /admin را بزن 🎉", "👮 You've been made an admin of the bot! Send /admin 🎉")
add("ad_notify_removed", "ℹ️ دسترسی ادمین تو برداشته شد.", "ℹ️ Your admin access was removed.")
add("ad_owner_ask", "🔁 شناسه‌ی عددی یا @نام‌کاربری مالک جدید را بفرست (باید قبلاً با ربات کار کرده باشد):\n⚠️ بعد از تأیید، تو دیگر مالک نخواهی بود.\n(/cancel برای انصراف)",
    "🔁 Send the new owner's numeric id or @username (they must have used the bot before):\n⚠️ After confirming, you will no longer be the owner.\n(/cancel to abort)")
add("ad_owner_confirm", "مالکیت به {who} منتقل شود؟", "Transfer ownership to {who}?")
add("ad_owner_done", "✅ مالک جدید: {who}", "✅ New owner: {who}")
add("ad_owner_notify_new", "👑 تو حالا مالک (ادمین اصلی) ربات هستی! /admin را بزن.", "👑 You are now the owner (main admin) of the bot! Send /admin.")
add("ad_owner_notify_old", "ℹ️ مالکیت ربات به {who} منتقل شد.", "ℹ️ Bot ownership was transferred to {who}.")
add("ad_owner_same", "این کاربر همین الان مالک است.", "That user is already the owner.")
add("a_denied", "🔒 این بخش فقط برای مالک است.", "🔒 This section is owner-only.")
add("su_menu", "💬 مخاطبین پشتیبانی\n\n1️⃣ اصلی: @{p}\n2️⃣ پشتیبان دوم: {b}\n\nاین‌ها در دکمه‌ی «پیام به ادمین» به کاربران نشان داده می‌شوند. اگر پشتیبان دوم تنظیم شود، هر دو دکمه با یک توضیح نمایش داده می‌شوند.",
    "💬 Support contacts\n\n1️⃣ Primary: @{p}\n2️⃣ Backup: {b}\n\nThese are used for the “Contact admin” button. If a backup is set, both buttons show with a short note.")
add("su_b_primary", "✏️ تغییر پشتیبان اصلی", "✏️ Edit primary"); add("su_b_backup", "✏️ تنظیم پشتیبان دوم", "✏️ Set backup")
add("su_b_primary", "✏️ تغییر پشتیبان اصلی", "✏️ Edit primary"); add("su_b_backup", "✏️ تنظیم پشتیبان دوم", "✏️ Set backup")
add("su_b_clear", "🧹 حذف پشتیبان دوم", "🧹 Remove backup")
add("su_ask", "✏️ نام‌کاربری تلگرام (مثلاً @example) را بفرست:\n(/cancel برای انصراف)", "✏️ Send the Telegram username (e.g. @example):\n(/cancel to abort)")
add("su_bad", "نام‌کاربری نامعتبر است (۵ تا ۳۲ حرف انگلیسی/عدد/_). دوباره بفرست یا /cancel.", "Invalid username (5–32 letters/digits/_). Send again or /cancel.")
add("su_saved", "✅ ذخیره شد.", "✅ Saved."); add("su_cleared", "🧹 پشتیبان دوم حذف شد.", "🧹 Backup support removed.")
add("su_saved", "✅ ذخیره شد.", "✅ Saved."); add("su_cleared", "🧹 پشتیبان دوم حذف شد.", "🧹 Backup support removed.")
add("su_none", "(تنظیم نشده)", "(not set)")

# ---- plan tier cards (display only; count required) ----
add("b_plans", "💎 پلن‌ها", "💎 Plans")
add("pp_head_user", "💰 پلن‌ها:", "💰 Plans:")
add("pp_user_line2", "{star}✨ {title} — {what} — {price}", "{star}✨ {title} — {what} — {price}")
add("pp_what_credits", "{n} استیکر", "{n} stickers")
add("pp_popular", "⭐ محبوب‌ترین", "⭐ Popular")
add("pp_popular_short", "⭐ ", "⭐ ")
add("plans_title", "💎 پلن‌های استیکرساز", "💎 Sticker plans")
add("plans_free", "🆓 <b>رایگان</b>\n🎟 {n} استیکر برای هر کاربر جدید", "🆓 <b>Free</b>\n🎟 {n} stickers for every new user")
add("plans_card", "✨ <b>{title}</b>\n🎟 {count} استیکر\n💵 {price}{dur}{feats}", "✨ <b>{title}</b>\n🎟 {count} stickers\n💵 {price}{dur}{feats}")
add("plans_none", "🌷 پلن‌های پولی به‌زودی اضافه می‌شوند. فعلاً از سهمیه‌ی رایگان و دعوت دوستان استفاده کن!", "🌷 Paid plans are coming soon. For now enjoy the free quota and invite friends!")
add("plans_footer", "💌 برای فعال‌سازی یک پلن به ادمین پیام بده و این شناسه‌ی عددی‌ات را بفرست:\n🆔 <code>{uid}</code>{note}",
    "💌 To activate a plan, message the admin and send your numeric ID:\n🆔 <code>{uid}</code>{note}")
add("pp_hidden", " · 🙈 مخفی تا پر شدن تعداد و قیمت", " · 🙈 hidden until count & price are set")
add("pp_mgr", "💰 قیمت‌ها و پلن‌ها\n\n{lines}\n\nهر پلن یک تعداد استیکر (اجباری) و یک متن قیمت دارد. پلن‌ها فقط نمایشی‌اند و فقط وقتی تعداد و قیمت پر شده باشد به کاربران نشان داده می‌شوند. ⬆️⬇️ برای تغییر ترتیب.",
    "💰 Prices & plans\n\n{lines}\n\nEvery plan has a REQUIRED sticker count and a price text. Plans are display-only and shown to users only once count and price are set. Use ⬆️⬇️ to reorder.")
add("pp_mgr_line", "{pos}. {star}{title} — {count} · {price}{dur}{hid}", "{pos}. {star}{title} — {count} · {price}{dur}{hid}")
add("pp_ask_title", "✏️ نام پلن را بفرست (مثلاً «پایه»):\n(/cancel برای انصراف)", "✏️ Send the plan name (e.g. “Basic”):\n(/cancel to abort)")
add("pp_ask_count", "🎟 تعداد استیکر این پلن را بفرست (عدد اجباری، بزرگ‌تر از صفر):", "🎟 Send the sticker count for this plan (required number, above zero):")
add("pp_ask_price", "💵 متن قیمت را بفرست (هر متن و هر واحد پولی که می‌خواهی):", "💵 Send the price text (any text, any currency you like):")
add("pp_ask_dur", "⏳ اختیاری: مدت را بنویس (مثلاً «ماهانه» یا «یک‌بار») یا رد کن:", "⏳ Optional: send a duration text (e.g. “per month” or “one-time”) or skip:")
add("pp_ask_feat", "🌟 اختیاری: یک خط ویژگی‌ها بنویس؛ با | یا ; یا خط جدید جدا کن (مثلاً «بدون واترمارک | پشتیبانی»):", "🌟 Optional: send a features line; separate with | or ; or new lines (e.g. “No watermark | Support”):")
add("pp_ask_pop", "⭐ این پلن با نشان «محبوب‌ترین» نمایش داده شود؟", "⭐ Show this plan with the “Popular” badge?")
add("pp_skip", "⏭ رد کردن", "⏭ Skip")
add("pp_added", "✅ پلن اضافه شد.", "✅ Plan added.")
add("pp_saved", "✅ پلن ذخیره شد.", "✅ Plan saved.")
add("pp_edit_menu", "✏️ ویرایش پلن #{id}\n\n{card}\n\n(برای پاک کردن مدت/ویژگی‌ها، «-» بفرست)", "✏️ Edit plan #{id}\n\n{card}\n\n(send “-” to clear duration/features)")
add("pp_e_title", "✏️ نام", "✏️ Name"); add("pp_e_count", "🎟 تعداد", "🎟 Count"); add("pp_e_price", "💵 قیمت", "💵 Price")
add("pp_e_dur", "⏳ مدت", "⏳ Duration"); add("pp_e_feat", "🌟 ویژگی‌ها", "🌟 Features")
add("pp_e_pop", "⭐ محبوب: {s}", "⭐ Popular: {s}")
add("pp_up", "⬆️", "⬆️"); add("pp_down", "⬇️", "⬇️")
add("pp_quick_credits", "{title} (+{n} 💎)", "{title} (+{n} 💎)")
add("pp_quick", "⚡ پلن‌ها (میان‌بر):", "⚡ Plans (quick):")
